package io.urlscan.client.model

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * Data Transfer Object representing a notification channel.
 * Channels are used to deliver notifications from subscriptions.
 *
 * @property id Unique ID of the channel (read-only, generated by server)
 * @property type Type of channel: "webhook" for HTTP integrations or "email" for email delivery
 * @property name Name of the channel
 * @property description Description of the channel
 * @property webhookURL The webhook URL for webhook-type channels (must start with http://, https://, or socks://)
 * @property frequency Frequency of notifications for this channel: live, hourly, or daily
 * @property emailAddresses List of email addresses for email-type channels
 * @property utcTime 24-hour UTC time for daily email delivery (e.g., "09:00")
 * @property isActive Whether the channel is currently active
 * @property isDefault Whether this is the default notification channel
 * @property ignoreTime Whether to ignore time constraints for notifications
 * @property weekDays Days of the week notifications will be sent (Monday-Sunday)
 * @property permissions Access control permissions (team:read, team:write)
 */
@Serializable
data class Channel(
    @SerialName("_id")
    val id: String? = null,
    val type: String,
    val name: String,
    val description: String? = null,
    val webhookURL: String? = null,
    val frequency: String? = null,
    val emailAddresses: List<String>? = null,
    val utcTime: String? = null,
    val isActive: Boolean = true,
    val isDefault: Boolean = false,
    val ignoreTime: Boolean = false,
    val weekDays: List<WeekDay>? = null,
    val permissions: List<TeamPermission>? = null
) {
    init {
        require(type.isNotBlank()) { "Type cannot be blank" }
        require(name.isNotBlank()) { "Name cannot be blank" }
        require(type.equals("webhook", ignoreCase = true) || type.equals("email", ignoreCase = true)) {
            "Type must be 'webhook' or 'email'"
        }
    }
}

/**
 * Data Transfer Object for channel creation/update requests.
 */
@Serializable
data class ChannelRequest(
    val channel: Channel
)

/**
 * Response wrapper for a single channel.
 */
@Serializable
data class ChannelResponse(
    val channel: Channel
)

/**
 * Response wrapper for channel list.
 */
@Serializable
internal data class ChannelsListResponse(
    val channels: List<Channel>
)

/**
 * Data Transfer Object containing channel statistics and metrics.
 *
 * @property totalChannels Total number of channels
 * @property webhookChannels Count of webhook-type channels
 * @property emailChannels Count of email-type channels
 * @property activeChannels Count of active channels
 * @property inactiveChannels Count of inactive channels
 * @property defaultChannels Count of channels marked as default
 */
@Serializable
data class ChannelStatistics(
    val totalChannels: Int,
    val webhookChannels: Int,
    val emailChannels: Int,
    val activeChannels: Int,
    val inactiveChannels: Int,
    val defaultChannels: Int
)
