package io.urlscan.client.model

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * Enumeration of notification frequencies for subscriptions.
 */
@Serializable
enum class SubscriptionFrequency {
    @SerialName("live") LIVE,
    @SerialName("hourly") HOURLY,
    @SerialName("daily") DAILY
}

/**
 * Enumeration of incident creation modes.
 */
@Serializable
enum class IncidentCreationMode {
    @SerialName("none") NONE,
    @SerialName("default") DEFAULT,
    @SerialName("always") ALWAYS,
    @SerialName("ignore-if-exists") IGNORE_IF_EXISTS
}

/**
 * Enumeration of incident watch keys.
 */
@Serializable
enum class IncidentWatchKey {
    @SerialName("scans/page.url") SCANS_PAGE_URL,
    @SerialName("scans/page.domain") SCANS_PAGE_DOMAIN,
    @SerialName("scans/page.ip") SCANS_PAGE_IP,
    @SerialName("scans/page.apexDomain") SCANS_PAGE_APEX_DOMAIN,
    @SerialName("hostnames/hostname") HOSTNAMES_HOSTNAME,
    @SerialName("hostnames/ip") HOSTNAMES_IP,
    @SerialName("hostnames/domain") HOSTNAMES_DOMAIN
}

/**
 * Data Transfer Object representing a Subscription.
 * Subscriptions automate notifications for Saved Searches through specified channels and frequencies.
 *
 * @property id Unique ID of the subscription (read-only, generated by server)
 * @property searchIds Array of Saved Search IDs associated with this subscription
 * @property frequency Frequency of notifications: live, hourly, or daily
 * @property emailAddresses Email addresses receiving the notifications
 * @property name Name of the subscription
 * @property description Description of the subscription
 * @property isActive Whether the subscription is currently active
 * @property ignoreTime Whether to ignore time constraints
 * @property weekDays Days of the week alerts will be generated (Monday-Sunday)
 * @property permissions Access control permissions (team:read, team:write)
 * @property channelIds Array of channel IDs associated with this subscription
 * @property incidentChannelIds Array of incident channel IDs for incident creation
 * @property incidentProfileId Incident Profile ID associated with this subscription
 * @property incidentVisibility Incident visibility for this subscription (unlisted, private)
 * @property incidentCreationMode How incidents should be created (none, default, always, ignore-if-exists)
 * @property incidentWatchKeys Source/key to watch in incidents
 */
@Serializable
data class Subscription(
    @SerialName("_id")
    val id: String? = null,
    val searchIds: List<String>,
    val frequency: SubscriptionFrequency,
    val emailAddresses: List<String>,
    val name: String,
    val description: String? = null,
    val isActive: Boolean,
    val ignoreTime: Boolean,
    val weekDays: List<String>? = null,
    val permissions: List<TeamPermission>? = null,
    val channelIds: List<String>? = null,
    val incidentChannelIds: List<String>? = null,
    val incidentProfileId: String? = null,
    val incidentVisibility: String? = null,
    val incidentCreationMode: IncidentCreationMode? = null,
    val incidentWatchKeys: IncidentWatchKey? = null
) {
    init {
        require(searchIds.isNotEmpty()) { "At least one search ID must be specified" }
        require(emailAddresses.isNotEmpty()) { "At least one email address must be specified" }
        require(name.isNotBlank()) { "Name cannot be blank" }
    }
}

/**
 * Data Transfer Object for subscription creation/update requests.
 */
@Serializable
data class SubscriptionRequest(
    val subscription: Subscription
)

/**
 * Response wrapper for a single subscription.
 */
@Serializable
data class SubscriptionResponse(
    val subscription: Subscription
)